project_id = "uiyjmjibshnkhwewtkoz"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.create-visit-payment]
verify_jwt = true

[functions.create-visit-invoice]
verify_jwt = true

[functions.ai-search-service]
verify_jwt = true

[functions.shorten-url]
verify_jwt = true

[functions.chatbot]
verify_jwt = false
