project_id = "uiyjmjibshnkhwewtkoz"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.create-visit-payment]
verify_jwt = true

[functions.create-visit-invoice]
verify_jwt = true

[functions.ai-search-service]
verify_jwt = true

[functions.shorten-url]
verify_jwt = true

[functions.chatbot]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = false

[functions.check-expired-reschedules]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.create-connect-account]
verify_jwt = true

[functions.create-visit-authorization]
verify_jwt = true

[functions.complete-first-visit]
verify_jwt = true

[functions.create-or-get-invoice]
verify_jwt = true

[functions.get-invoice]
verify_jwt = true

[functions.send-invoice-to-client]
verify_jwt = true
